### ISSUE TITLE
CI workflow action fails on each project

### ISSUE THREAD

**Issue by borisPristupa** [Orfac/graphql-client#10]
Любой проект падает на [этом workflow action](https://github.com/Orfac/graphql-client/actions?query=workflow%3ACI). Ещё и на почту об этом уведомления постоянно приходят - кругом плохо. 

[Вот до чего удалось докопаться](https://github.com/Orfac/graphql-client/runs/452727818?check_suite_focus=true#step:3:26), но причина происходящего остаётся неясной

![image](https://user-images.githubusercontent.com/34197339/74739777-9ea75980-526a-11ea-9403-4fd322959ee6.png)

**Comment by Orfac** [comment]
fixed in c37661139d28453c1c5394eed1e2516ba3046e91
